### PR TITLE
Add images that can be used directly by end users

### PR DESCRIPTION
**Pull request by yuvipanda**
Setting up docker images that run applications well can be a little complex, so we provide a simple base image that makes that easy. In addition, we also provide some simple derived images that have popular datascience related desktop applications set up correctly and ready to use.

The images will be published *only* to [quay.io](https://quay.io/organization/jupyter-remote-desktop-proxy), to make sure people don't run into pulling limits from Dockerhub.

## Base image `quay.io/jupyter-remote-desktop-proxy/base`

This image is based off the `jupyter/minimal-notebook` image maintained as part of jupyter/docker-stacks, and adds the following features:

1. The lightweight [XFCE4 desktop environment](https://www.xfce.org/)
2. The [Firefox web browser](https://www.mozilla.org/en-US/firefox/new/)
3. A helper script to setup [.desktop](https://wiki.archlinux.org/title/desktop_entries) files correctly, so applications can show up in the Desktop and Application launcher.
3. A helper script to setup [MIME associations](https://wiki.archlinux.org/title/XDG_MIME_Applications) correctly, so users can double click certain kinds of files and have them open in specific applications.

## QGIS image `quay.io/jupyter-remote-desktop-proxy/qgis`

This image is based off the base image, and installs the popular [QGIS](https://qgis.org/en/site/) application. A desktop launcher icon is provided, along with filetype associations so users can double click most files that can be opend via QGIS and they will be!
Brings in https://github.com/jupyter/docker-stacks/pull/1961

## Automated building

There's a `build.py` that automatically builds and pushes the images, dealing with dependencies as appropriate.

Thanks to @MattF-NSIDC for figuring out a lot of the qgis desktop & mime stuff.

## TODO

- [ ] Document how to inherit from the base image
- [x] Document *policy* for what applications get their own image here
- [x] Dynamic image tagging based on version of package installed inside, based on code in https://github.com/jupyter/docker-stacks/tree/main/tagging
- [ ] Move the default container `Dockerfile` to be purely about testing https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/58

## TODO at a later time

- [ ] ARM image building support
- [ ] Automated *integration* tests - these are difficult as we'll have to launch a browser, connect to the VNC server in the container, and somehow visually verify things work.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I still need to test that the .desktop associations and mime associations actually happen when used with a JupyterHub!

**Comment by consideRatio** [comment]
Wieeee nice work on this @yuvipanda! I opened #55 to discuss image adding policy to offload this PR from such discussion.

**Comment by manics** [comment]
What do you think about moving these to a separate repo? I expect jupyter-remote-desktop-proxy to have relatively few updates and releases whereas these images are likely to see ore frequent updates, and will probably have a different tagging scheme to the pypi package.

**Comment by yuvipanda** [comment]
After reflecting on this for a while, I've written https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/55#issuecomment-1859368976 and am going to close this PR 😞

**Comment by yuvipanda** [comment]
@manics in practice that's what I think I'll end up doing :)

**Pull request closed without merging**
