### PR TITLE
Close clipboard if clicked outside

### PR DESCRIPTION
**Pull request by manics**
I think it's more natural for the clipboard to automatically close when you click the desktop outside it, e.g. to paste something into the desktop. Currently you have to click the button again to close it.

### CODE REVIEW

**Comment by yuvipanda** [comment]
https://github.com/user-attachments/assets/bc3d7710-424f-4f03-b213-1c9ffc0ce1f4

This only seems to close it if clicked on the canvas, and not on the background or elsewhere on the bar.

Can we attach the event to `body` or similar so it hides when clicked anywhere outside?

**Comment by manics** [comment]
I originally restricted it to the canvas to reduce the chance of complex interactions if we added more items to the menu bar or background area in future. I've changed it to `document.body` in the last commit.

**Comment by manics** [comment]
This will require attaching handlers to multiple elements, as NoVNC attaches an onclick handler to `canvas` with `stopPropagation`, so the handler on the parent element isn't called.

**Comment by yuvipanda** [comment]
Tested and it works! Thank you @manics

**Pull request merged**
