### PR TITLE
Cleanup the UI to be much nicer

### PR DESCRIPTION
**Pull request by yuvipanda**
Built on top of https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/77

image

This PR is a combination of JS cleanup as well as UI cleanup. 

- Remove ability to connect to arbitrary hosts and ports via query params. We already required websockify anyway, so this never worked. Plus, we only care about using the viewer for our own purposes, not as a general purpose novnc thing
- Get rid of the ctrlAltDelete function. It's not particularly useful in this context. I will work on adding more UI here, but this location is a good place for other buttons
- Add eslint for pre-commit and fix the one issue it found
- Stop showing the 'desktop name' up top. This is the hostname, and not particularly useful.
- Have a cleaner looking menu
- Put the Jupyter Logo in there, clicking which takes you back to jupyterlab / notebook!
- Use [floating-ui](https://floating-ui.com/) to make the clipboard popover *much* nicer. This is the same library used by bootstrap (used to be popper.js). I actually spent some time trying to port the whole thing to bootstrap, but that caused more problems than it solved.

### CODE REVIEW

**Comment by yuvipanda** [comment]
I wanna move `js` to `src` but that's likely to cause a bunch of knock on effects in #79 so I'll do that after.

**Comment by yuvipanda** [comment]
@manics when I tried it, it showed me the logout window. And if I tried to logout, it mostly just bricked my desktop session - I think it stopped dbus and xfce-session, but not anything else. That's one of the primary reasons I removed it, as our handling of how these processes are supervised (they just double fork and go on their merry way) doesn't help.

I'm going to add a dropdown menu with lesser used options - primarily intended for a checkbox for 'scale to fit'. But I can put a ctrl-alt-delete button there too. Are you ok with that coming in a later PR?

**Review by manics — APPROVED** [review]
OK! I've adding a tracking issue https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/83

**Comment by yuvipanda** [comment]
Yay, thank you, @manics :)

**Pull request merged**
