### PR TITLE
Add a shared clipboard

### PR DESCRIPTION
**Pull request by manics**
Adds a textarea that acts as a shared bi-directional clipboard. This is based on `vnc.html`:
- https://github.com/novnc/noVNC/blob/v1.2.0/vnc.html#L143-L157
- https://github.com/novnc/noVNC/blob/v1.2.0/app/ui.js#L924-L966

image

### CODE REVIEW

**Comment by manics** [comment]
This also means you can share the link to the current instance with a browser inside itself :smile: 
image

**Comment by fperez** [comment]
Thanks @yuvipanda for pointing me here! Glad to see there's a start on this one - it's not absolutely critical, but will become a bigger and bigger annoyance the more we try to do "on the inside" of the hubs. 

I've resorted to using the hub's firefox a lot more precisely so I can move information around, since at least inside this does work fine...

**Comment by yuvipanda** [comment]
Just tested this, and it seems to work :) We can work on the styling later! Thanks a lot, @manics!

**Comment by fperez** [comment]
Many thanks! Has this been released? I was just about to freshen the stat159 image and it would be nice to have this finally solved :)

**Comment by yuvipanda** [comment]
@fperez not yet, but maybe there may be one tomorrow! https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/20#issuecomment-1396481381

**Comment by fperez** [comment]
Awesome, thx!

**Comment by yuvipanda** [comment]
@fperez done! It has a different name though - https://pypi.org/project/jupyter-remote-desktop-proxy/

**Comment by fperez** [comment]
Awesome, thx!! I just updated [the stat159 env](https://github.com/berkeley-dsep-infra/datahub/pull/4132), can I replace `jupyter-desktop-server==0.1.3`with `jupyter-remote-desktop-proxy==1.0.0` now?

And if so, do you have a conda package for it yet, or should I go with pip for the time being?

cc @shaneknapp @balajialg in case this update is useful for other hubs than 159.

**Comment by yuvipanda** [comment]
@fperez yep, just that change would do. It is a bit complex to package on conda, might be a while! So still gotta use pip

**Comment by fperez** [comment]
Thx Yuvi, np!

**Comment by satra** [comment]
thanks @yuvipanda - just incorporated into dandihub. required the websockify piece from conda-forge as instructed in the readme. will be very helpful to folks.

**Pull request merged**
